// Georgian Language Learning Data

const ALPHABET = [
  { letter: 'ა', roman: 'a', ru: 'а', hint: 'как «а» в «арбуз»', hint_en: 'like "a" in "car"', example: 'ანი (ani) — имя' },
  { letter: 'ბ', roman: 'b', ru: 'б', hint: 'как «б» в «банан»', hint_en: 'like "b" in "ball"', example: 'ბათუმი (batumi) — Батуми' },
  { letter: 'გ', roman: 'g', ru: 'г', hint: 'как «г» в «город»', hint_en: 'like "g" in "go"', example: 'გული (guli) — сердце' },
  { letter: 'დ', roman: 'd', ru: 'д', hint: 'как «д» в «дом»', hint_en: 'like "d" in "dog"', example: 'დედა (deda) — мама' },
  { letter: 'ე', roman: 'e', ru: 'е', hint: 'как «э» в «это»', hint_en: 'like "e" in "bed"', example: 'ერთი (erti) — один' },
  { letter: 'ვ', roman: 'v', ru: 'в', hint: 'как «в» в «вода»', hint_en: 'like "v" in "vine"', example: 'ვარდი (vardi) — роза' },
  { letter: 'ზ', roman: 'z', ru: 'з', hint: 'как «з» в «зима»', hint_en: 'like "z" in "zero"', example: 'ზღვა (zghva) — море' },
  { letter: 'თ', roman: 'th', ru: 'т (придых.)', hint: 'мягкое «т» с выдохом воздуха', hint_en: 'aspirated "t" — breathe out as you say it', example: 'თბილისი (tbilisi) — Тбилиси' },
  { letter: 'ი', roman: 'i', ru: 'и', hint: 'как «и» в «игра»', hint_en: 'like "ee" in "feet"', example: 'ივანე (ivane) — Иване' },
  { letter: 'კ', roman: "k'", ru: 'к (смычн.)', hint: 'резкое «к», без выдоха', hint_en: 'ejective "k" — sharp click, no breath', example: 'კაცი (k\'atsi) — мужчина' },
  { letter: 'ლ', roman: 'l', ru: 'л', hint: 'как «л» в «лес»', hint_en: 'like "l" in "lake"', example: 'ლომი (lomi) — лев' },
  { letter: 'მ', roman: 'm', ru: 'м', hint: 'как «м» в «мама»', hint_en: 'like "m" in "mom"', example: 'მზე (mze) — солнце' },
  { letter: 'ნ', roman: 'n', ru: 'н', hint: 'как «н» в «нос»', hint_en: 'like "n" in "nose"', example: 'ნინო (nino) — Нино' },
  { letter: 'ო', roman: 'o', ru: 'о', hint: 'как «о» в «окно»', hint_en: 'like "o" in "more"', example: 'ოჯახი (ojakhi) — семья' },
  { letter: 'პ', roman: "p'", ru: 'п (смычн.)', hint: 'резкое «п», без выдоха', hint_en: 'ejective "p" — sharp click, no breath', example: 'პური (p\'uri) — хлеб' },
  { letter: 'ჟ', roman: 'zh', ru: 'ж', hint: 'как «ж» в «жара»', hint_en: 'like "s" in "measure" or "zh"', example: 'ჟინი (zhini) — желание' },
  { letter: 'რ', roman: 'r', ru: 'р', hint: 'вибрирующее «р»', hint_en: 'rolled "r" like in Spanish', example: 'რქა (rqa) — рог' },
  { letter: 'ს', roman: 's', ru: 'с', hint: 'как «с» в «сад»', hint_en: 'like "s" in "sun"', example: 'სახლი (sakhli) — дом' },
  { letter: 'ტ', roman: "t'", ru: 'т (смычн.)', hint: 'резкое «т», без выдоха', hint_en: 'ejective "t" — sharp click, no breath', example: 'ტყე (t\'qe) — лес' },
  { letter: 'უ', roman: 'u', ru: 'у', hint: 'как «у» в «утро»', hint_en: 'like "oo" in "moon"', example: 'უბანი (ubani) — район' },
  { letter: 'ფ', roman: 'p', ru: 'п (придых.)', hint: 'мягкое «п» с выдохом, почти «ф»', hint_en: 'aspirated "p" — breathe out as you say it', example: 'ფული (puli) — деньги' },
  { letter: 'ქ', roman: 'q', ru: 'к (придых.)', hint: 'мягкое «к» с выдохом', hint_en: 'aspirated "k" — breathe out as you say it', example: 'ქალაქი (kalaki) — город' },
  { letter: 'ღ', roman: 'gh', ru: 'г (фрикат.)', hint: 'глубокое «г», почти как «р» во французском', hint_en: 'guttural "gh", like French "r" in Paris', example: 'ღვინო (ghvino) — вино' },
  { letter: 'ყ', roman: "q'", ru: 'гортанн. к', hint: 'гортанное «к» из глубины горла', hint_en: 'ejective guttural "k" — from deep in the throat', example: 'ყავა (q\'ava) — кофе' },
  { letter: 'შ', roman: 'sh', ru: 'ш', hint: 'как «ш» в «шум»', hint_en: 'like "sh" in "shoe"', example: 'შვილი (shvili) — дитя' },
  { letter: 'ჩ', roman: 'ch', ru: 'ч (придых.)', hint: 'мягкое «ч» с выдохом', hint_en: 'aspirated "ch" — like "ch" with a puff of air', example: 'ჩაი (chai) — чай' },
  { letter: 'ც', roman: 'ts', ru: 'ц (придых.)', hint: 'мягкое «ц» с выдохом', hint_en: 'aspirated "ts" — like "ts" in "cats" with air', example: 'ცხოვრება (tskhovreba) — жизнь' },
  { letter: 'ძ', roman: 'dz', ru: 'дз', hint: 'как «дз» в «дзюдо»', hint_en: 'like "dz" in "adze" or "ds" in "odds"', example: 'ძმა (dzma) — брат' },
  { letter: 'წ', roman: "ts'", ru: 'ц (смычн.)', hint: 'резкое «ц», без выдоха', hint_en: 'ejective "ts" — sharp, no breath', example: 'წყალი (ts\'q\'ali) — вода' },
  { letter: 'ჭ', roman: "ch'", ru: 'ч (смычн.)', hint: 'резкое «ч», без выдоха', hint_en: 'ejective "ch" — sharp, no breath', example: 'ჭამა (ch\'ama) — еда' },
  { letter: 'ხ', roman: 'kh', ru: 'х', hint: 'как «х» в «хорошо»', hint_en: 'like "ch" in Scottish "loch" or "Bach"', example: 'ხინკალი (khinkali) — хинкали' },
  { letter: 'ჯ', roman: 'j', ru: 'дж', hint: 'как «дж» в «джаз»', hint_en: 'like "j" in "jazz"', example: 'ჯამი (jami) — чашка' },
  { letter: 'ჰ', roman: 'h', ru: 'х (мягк.)', hint: 'очень мягкое «х», почти «г»', hint_en: 'like "h" in "hotel"', example: 'ჰაერი (haeri) — воздух' },
];

const PHRASES = {
  greeting: {
    title: 'Приветствия',
    title_en: 'Greetings',
    icon: '👋',
    items: [
      { ka: 'გამარჯობა', rom: 'gamarjoba', ru: 'Здравствуйте / Привет', en: 'Hello / Hi', note: 'Самое универсальное приветствие', note_en: 'The most universal Georgian greeting' },
      { ka: 'გამარჯობათ', rom: 'gamarjobat', ru: 'Здравствуйте (вежливо)', en: 'Hello (formal)', note: 'Для старших и незнакомых', note_en: 'Use with elders and strangers' },
      { ka: 'სალამი', rom: 'salami', ru: 'Привет (неформально)', en: 'Hey / Hi (casual)', note: 'Среди друзей', note_en: 'Among friends' },
      { ka: 'დილა მშვიდობისა', rom: 'dila mshvidobisa', ru: 'Доброе утро', en: 'Good morning', note: '' },
      { ka: 'საღამო მშვიდობისა', rom: 'saghamo mshvidobisa', ru: 'Добрый вечер', en: 'Good evening', note: '' },
      { ka: 'ღამე მშვიდობისა', rom: 'ghame mshvidobisa', ru: 'Спокойной ночи', en: 'Good night', note: '' },
      { ka: 'ნახვამდის', rom: 'nakhvamdis', ru: 'До свидания', en: 'Goodbye', note: '' },
      { ka: 'კარგად იყავი', rom: 'kargad iq\'avi', ru: 'Будь здоров/а', en: 'Take care / Stay well', note: 'Прощание', note_en: 'A warm farewell' },
      { ka: 'როგორ ხარ?', rom: 'rogor khar?', ru: 'Как дела?', en: 'How are you?', note: '' },
      { ka: 'კარგად, გმადლობ', rom: 'kargad, gmadlob', ru: 'Хорошо, спасибо', en: 'Fine, thank you', note: 'Ответ на «как дела»', note_en: 'Reply to "how are you?"' },
      { ka: 'სახელი მქვია...', rom: 'sakheli mqvia...', ru: 'Меня зовут...', en: 'My name is...', note: 'Вставьте своё имя', note_en: 'Insert your own name' },
      { ka: 'სად ხარ?', rom: 'sad khar?', ru: 'Где ты?', en: 'Where are you?', note: '' },
      { ka: 'რუსულად ლაპარაკობ?', rom: 'rusulad laparakob?', ru: 'Говоришь по-русски?', en: 'Do you speak Russian?', note: '' },
      { ka: 'ვერ გავიგე', rom: 'ver gavige', ru: 'Не понял/а', en: 'I didn\'t understand', note: '' },
      { ka: 'ნელა, გთხოვთ', rom: 'nela, gtkhovt', ru: 'Говорите медленнее, пожалуйста', en: 'Please speak slower', note: '' },
      { ka: 'გაიმეორეთ, გთხოვთ', rom: 'gaimeoreth, gtkhovt', ru: 'Повторите, пожалуйста', en: 'Please repeat that', note: '' },
    ]
  },
  polite: {
    title: 'Вежливость',
    title_en: 'Politeness',
    icon: '🙏',
    items: [
      { ka: 'გმადლობ', rom: 'gmadlob', ru: 'Спасибо', en: 'Thank you', note: 'Неформально', note_en: 'Informal' },
      { ka: 'გმადლობთ', rom: 'gmadlobt', ru: 'Спасибо (вежливо)', en: 'Thank you (formal)', note: 'Формальная форма', note_en: 'Formal form' },
      { ka: 'დიდი მადლობა', rom: 'didi madloba', ru: 'Большое спасибо', en: 'Thank you very much', note: '' },
      { ka: 'ბოდიში', rom: 'bodishi', ru: 'Извините / Простите', en: 'Excuse me / Sorry', note: 'Для привлечения внимания и извинений', note_en: 'To get attention or apologise' },
      { ka: 'კი', rom: 'ki', ru: 'Да', en: 'Yes', note: '' },
      { ka: 'არა', rom: 'ara', ru: 'Нет', en: 'No', note: '' },
      { ka: 'გთხოვთ', rom: 'gtkhovt', ru: 'Пожалуйста (просьба)', en: 'Please (request)', note: 'При обращении с просьбой', note_en: 'When making a request' },
      { ka: 'არაფერს', rom: 'arapars', ru: 'Пожалуйста (ответ)', en: 'You\'re welcome', note: 'Ответ на «спасибо»', note_en: 'Reply to "thank you"' },
      { ka: 'რა თქმა უნდა', rom: 'ra tkma unda', ru: 'Конечно', en: 'Of course', note: '' },
      { ka: 'პრობლემა არ არის', rom: 'p\'roblema ar aris', ru: 'Нет проблем', en: 'No problem', note: '' },
      { ka: 'გავიგე', rom: 'gavige', ru: 'Понял/а', en: 'I understand / Got it', note: '' },
      { ka: 'არ ვიცი', rom: 'ar vitsi', ru: 'Не знаю', en: 'I don\'t know', note: '' },
      { ka: 'მოიცა', rom: 'moitsa', ru: 'Подождите', en: 'Wait / Hold on', note: '' },
      { ka: 'შემოდით, გთხოვთ', rom: 'shemodith, gtkhovt', ru: 'Входите, пожалуйста', en: 'Come in, please', note: '' },
    ]
  },
  food: {
    title: 'Еда и рестораны',
    title_en: 'Food & Restaurants',
    icon: '🍽️',
    items: [
      { ka: 'ხინკალი', rom: 'khinkali', ru: 'Хинкали', en: 'Khinkali', note: 'Грузинские пельмени — must try!', note_en: 'Georgian dumplings — an absolute must try!' },
      { ka: 'ხაჭაპური', rom: 'khachapuri', ru: 'Хачапури', en: 'Khachapuri', note: 'Сырная лепёшка', note_en: 'Cheese-filled bread' },
      { ka: 'მწვადი', rom: 'mtsvadi', ru: 'Мцвади (шашлык)', en: 'Mtsvadi (Georgian BBQ)', note: 'Грузинский шашлык на виноградной лозе', note_en: 'Grilled on grapevine wood' },
      { ka: 'ლობიანი', rom: 'lobiani', ru: 'Лобиани', en: 'Lobiani', note: 'Лепёшка с фасолью', note_en: 'Bread filled with spiced beans' },
      { ka: 'ბადრიჯანი', rom: 'badrижani', ru: 'Баклажан с орехами', en: 'Badrijani (eggplant with walnut)', note: 'Классическая закуска', note_en: 'Classic cold starter' },
      { ka: 'სუპი', rom: 'supi', ru: 'Суп', en: 'Soup', note: '' },
      { ka: 'სალათი', rom: 'salati', ru: 'Салат', en: 'Salad', note: '' },
      { ka: 'ხორცი', rom: 'khortsi', ru: 'Мясо', en: 'Meat', note: '' },
      { ka: 'თევზი', rom: 'tevzi', ru: 'Рыба', en: 'Fish', note: '' },
      { ka: 'ყველი', rom: 'q\'veli', ru: 'Сыр', en: 'Cheese', note: '' },
      { ka: 'ღვინო', rom: 'ghvino', ru: 'Вино', en: 'Wine', note: 'Грузия — родина вина', note_en: 'Georgia is the birthplace of wine' },
      { ka: 'წყალი', rom: 'ts\'q\'ali', ru: 'Вода', en: 'Water', note: '' },
      { ka: 'ყავა', rom: 'q\'ava', ru: 'Кофе', en: 'Coffee', note: '' },
      { ka: 'ჩაი', rom: 'chai', ru: 'Чай', en: 'Tea', note: '' },
      { ka: 'პური', rom: 'p\'uri', ru: 'Хлеб', en: 'Bread', note: '' },
      { ka: 'ანგარიში, გთხოვთ', rom: 'angarishi, gtkhovt', ru: 'Счёт, пожалуйста', en: 'The bill, please', note: 'В ресторане', note_en: 'In a restaurant' },
      { ka: 'გემრიელია!', rom: 'gemrielial', ru: 'Вкусно!', en: 'It\'s delicious!', note: 'Хозяин будет рад!', note_en: 'The host will be delighted!' },
      { ka: 'გაუმარჯოს!', rom: 'gaumarjos!', ru: 'За здоровье! / Ваше здоровье!', en: 'Cheers! / To your health!', note: 'Грузинский тост', note_en: 'The Georgian toast' },
      { ka: 'ვეგეტარიანელი ვარ', rom: 'vegetarianeli var', ru: 'Я вегетарианец/ка', en: 'I\'m vegetarian', note: '' },
      { ka: 'ხორცის გარეშე', rom: 'khortsis gareshe', ru: 'Без мяса', en: 'Without meat', note: '' },
      { ka: 'კინძი არ მინდა', rom: 'kindzi ar minda', ru: 'Без кинзы', en: 'No coriander / No cilantro', note: 'Полезно если не любите кинзу', note_en: 'Useful if you dislike cilantro' },
      { ka: 'სასადილო', rom: 'sasadilo', ru: 'Ресторан / Столовая', en: 'Restaurant / Canteen', note: '' },
      { ka: 'მენიუ', rom: 'meniu', ru: 'Меню', en: 'Menu', note: '' },
    ]
  },
  navigation: {
    title: 'Ориентирование',
    title_en: 'Getting Around',
    icon: '🗺️',
    items: [
      { ka: 'სად არის...?', rom: 'sad aris...?', ru: 'Где находится...?', en: 'Where is...?', note: '' },
      { ka: 'მარცხნივ', rom: 'martskhniv', ru: 'Налево', en: 'Left', note: '' },
      { ka: 'მარჯვნივ', rom: 'marjvniv', ru: 'Направо', en: 'Right', note: '' },
      { ka: 'პირდაპირ', rom: 'pirdapir', ru: 'Прямо', en: 'Straight ahead', note: '' },
      { ka: 'აქ', rom: 'ak', ru: 'Здесь', en: 'Here', note: '' },
      { ka: 'იქ', rom: 'ik', ru: 'Там', en: 'There', note: '' },
      { ka: 'ახლოს', rom: 'akhlos', ru: 'Близко', en: 'Near / Close', note: '' },
      { ka: 'შორს', rom: 'shors', ru: 'Далеко', en: 'Far', note: '' },
      { ka: 'გაჩერება', rom: 'gachereba', ru: 'Остановка', en: 'Bus stop', note: '' },
      { ka: 'მეტრო', rom: 'metro', ru: 'Метро', en: 'Metro / Subway', note: '' },
      { ka: 'ავტობუსი', rom: 'avtobusi', ru: 'Автобус', en: 'Bus', note: '' },
      { ka: 'მარშრუტკა', rom: 'marshrutka', ru: 'Маршрутка', en: 'Marshrutka (minibus)', note: 'Основной транспорт в городах', note_en: 'The main city transport' },
      { ka: 'ტაქსი', rom: 'taksi', ru: 'Такси', en: 'Taxi', note: '' },
      { ka: 'მატარებელი', rom: 'matarebeli', ru: 'Поезд', en: 'Train', note: '' },
      { ka: 'აეროპორტი', rom: 'aerop\'orti', ru: 'Аэропорт', en: 'Airport', note: '' },
      { ka: 'სასტუმრო', rom: 'sastumro', ru: 'Гостиница / Отель', en: 'Hotel', note: '' },
      { ka: 'რამდენი ჯდება?', rom: 'ramdeni jdeba?', ru: 'Сколько стоит проезд?', en: 'How much is the fare?', note: '' },
      { ka: 'გამიჩერეთ აქ', rom: 'gamichereth ak', ru: 'Остановите здесь', en: 'Stop here please', note: 'В такси/маршрутке', note_en: 'In a taxi or minibus' },
      { ka: 'ეს სწორი გზაა?', rom: 'essts\'ori gzaa?', ru: 'Это правильная дорога?', en: 'Is this the right way?', note: '' },
    ]
  },
  shopping: {
    title: 'Покупки',
    title_en: 'Shopping',
    icon: '🛍️',
    items: [
      { ka: 'რამდენი ღირს?', rom: 'ramdeni ghirs?', ru: 'Сколько стоит?', en: 'How much does it cost?', note: '' },
      { ka: 'ძვირია', rom: 'dzvir\'ia', ru: 'Дорого', en: 'It\'s expensive', note: '' },
      { ka: 'ძალიან ძვირია', rom: 'dzalian dzvir\'ia', ru: 'Очень дорого', en: 'It\'s very expensive', note: '' },
      { ka: 'იაფია', rom: 'iapia', ru: 'Дёшево', en: 'It\'s cheap', note: '' },
      { ka: 'ფასი', rom: 'p\'asi', ru: 'Цена', en: 'Price', note: '' },
      { ka: 'ფასდათმობა', rom: 'p\'asdathmoba', ru: 'Скидка', en: 'Discount', note: '' },
      { ka: 'მინდა...', rom: 'minda...', ru: 'Я хочу...', en: 'I want...', note: '' },
      { ka: 'გაქვთ...?', rom: 'gakvt...?', ru: 'У вас есть...?', en: 'Do you have...?', note: '' },
      { ka: 'ავიღებ', rom: 'avigheb', ru: 'Я возьму это', en: 'I\'ll take it', note: '' },
      { ka: 'ბაზარი', rom: 'bazari', ru: 'Базар / Рынок', en: 'Market / Bazaar', note: '' },
      { ka: 'მაღაზია', rom: 'maghazia', ru: 'Магазин', en: 'Shop / Store', note: '' },
      { ka: 'ფული', rom: 'p\'uli', ru: 'Деньги', en: 'Money', note: '' },
      { ka: 'ლარი', rom: 'lari', ru: 'Лари (валюта)', en: 'Lari (currency)', note: 'Грузинская валюта', note_en: 'Georgian national currency' },
      { ka: 'ხურდა', rom: 'khurda', ru: 'Сдача', en: 'Change (money)', note: '' },
      { ka: 'ქვითარი', rom: 'kvitari', ru: 'Чек / Квитанция', en: 'Receipt', note: '' },
      { ka: 'ბარათი', rom: 'barati', ru: 'Карта (банковская)', en: 'Bank card', note: '' },
      { ka: 'ნაღდი ფული', rom: 'naghdi p\'uli', ru: 'Наличные', en: 'Cash', note: '' },
    ]
  },
  emergency: {
    title: 'Экстренные фразы',
    title_en: 'Emergency Phrases',
    icon: '🆘',
    items: [
      { ka: 'დამეხმარეთ!', rom: 'damekhmaret!', ru: 'Помогите!', en: 'Help!', note: '' },
      { ka: 'ექიმი', rom: 'ekimi', ru: 'Врач', en: 'Doctor', note: '' },
      { ka: 'საავადმყოფო', rom: 'saavadmq\'opo', ru: 'Больница', en: 'Hospital', note: '' },
      { ka: 'აფთიაქი', rom: 'aptiaki', ru: 'Аптека', en: 'Pharmacy', note: '' },
      { ka: 'პოლიცია', rom: 'p\'olitsia', ru: 'Полиция', en: 'Police', note: '' },
      { ka: 'ცეცხლი!', rom: 'tsetskhli!', ru: 'Пожар!', en: 'Fire!', note: '' },
      { ka: 'სასწრაფო დახმარება', rom: 'sasts\'rapo dakhmmareba', ru: 'Скорая помощь', en: 'Ambulance', note: 'Телефон: 112', note_en: 'Emergency number: 112' },
      { ka: 'მე ვარ დაკარგული', rom: 'me var dak\'arguli', ru: 'Я потерялся/ась', en: 'I\'m lost', note: '' },
      { ka: 'ავადმყოფი ვარ', rom: 'avadmq\'opi var', ru: 'Я болен/больна', en: 'I\'m sick / I\'m ill', note: '' },
      { ka: 'მტკივა', rom: 'mtk\'iva', ru: 'Мне больно', en: 'It hurts / I\'m in pain', note: '' },
      { ka: 'ქურდობა', rom: 'kurdoba', ru: 'Кража', en: 'Theft / Robbery', note: 'Если что-то украли', note_en: 'If something was stolen' },
      { ka: 'დაიკარგა ჩემი ჩანთა', rom: 'daik\'arga chemi chanta', ru: 'Пропала моя сумка', en: 'My bag is missing / gone', note: '' },
      { ka: 'მჭირდება თარჯიმანი', rom: 'mchirdeba tarjimani', ru: 'Мне нужен переводчик', en: 'I need a translator', note: '' },
    ]
  },
  accommodation: {
    title: 'Жильё и отель',
    title_en: 'Accommodation',
    icon: '🏨',
    items: [
      { ka: 'ოთახი', rom: 'otakhi', ru: 'Комната / Номер', en: 'Room', note: '' },
      { ka: 'ოთახი ერთი ადამიანისთვის', rom: 'otakhi erti adamianistvis', ru: 'Одноместный номер', en: 'Single room', note: '' },
      { ka: 'ოთახი ორი ადამიანისთვის', rom: 'otakhi ori adamianistvis', ru: 'Двухместный номер', en: 'Double room', note: '' },
      { ka: 'დაჯავშნა', rom: 'dajav\'shna', ru: 'Бронирование', en: 'Booking / Reservation', note: '' },
      { ka: 'შემოწმება', rom: 'shemotsmeba', ru: 'Заезд (check-in)', en: 'Check-in', note: '' },
      { ka: 'გამოწმება', rom: 'gamotsmeba', ru: 'Выезд (check-out)', en: 'Check-out', note: '' },
      { ka: 'გასაღები', rom: 'gasaghebi', ru: 'Ключ', en: 'Key', note: '' },
      { ka: 'Wi-Fi პაროლი', rom: 'wi-fi p\'aroli', ru: 'Пароль от Wi-Fi', en: 'Wi-Fi password', note: '' },
      { ka: 'სარეცხი', rom: 'saretskhi', ru: 'Прачечная', en: 'Laundry', note: '' },
      { ka: 'სადილი შედის?', rom: 'sadili shedis?', ru: 'Завтрак включён?', en: 'Is breakfast included?', note: '' },
      { ka: 'სად არის ლიფტი?', rom: 'sad aris lipti?', ru: 'Где лифт?', en: 'Where is the elevator?', note: '' },
      { ka: 'ოთახი ძალიან ხმაურიანია', rom: 'otakhi dzalian khmaurianial', ru: 'Номер очень шумный', en: 'The room is very noisy', note: '' },
    ]
  },
  numbers: {
    title: 'Числа и время',
    title_en: 'Numbers & Time',
    icon: '🔢',
    items: [
      { ka: 'ერთი', rom: 'erti', ru: 'Один (1)', en: 'One (1)', note: '' },
      { ka: 'ორი', rom: 'ori', ru: 'Два (2)', en: 'Two (2)', note: '' },
      { ka: 'სამი', rom: 'sami', ru: 'Три (3)', en: 'Three (3)', note: '' },
      { ka: 'ოთხი', rom: 'otkhi', ru: 'Четыре (4)', en: 'Four (4)', note: '' },
      { ka: 'ხუთი', rom: 'khuti', ru: 'Пять (5)', en: 'Five (5)', note: '' },
      { ka: 'ათი', rom: 'ati', ru: 'Десять (10)', en: 'Ten (10)', note: '' },
      { ka: 'ოცი', rom: 'otsi', ru: 'Двадцать (20)', en: 'Twenty (20)', note: 'Система счёта основана на 20!', note_en: 'Georgian counting is based on 20!' },
      { ka: 'ასი', rom: 'asi', ru: 'Сто (100)', en: 'Hundred (100)', note: '' },
      { ka: 'ათასი', rom: 'atasi', ru: 'Тысяча (1000)', en: 'Thousand (1000)', note: '' },
      { ka: 'რომელ საათზე?', rom: 'romel saatze?', ru: 'В котором часу?', en: 'At what time?', note: '' },
      { ka: 'დღეს', rom: 'dghes', ru: 'Сегодня', en: 'Today', note: '' },
      { ka: 'ხვალ', rom: 'khval', ru: 'Завтра', en: 'Tomorrow', note: '' },
      { ka: 'გუშინ', rom: 'gushin', ru: 'Вчера', en: 'Yesterday', note: '' },
      { ka: 'ახლა', rom: 'akhla', ru: 'Сейчас', en: 'Now', note: '' },
      { ka: 'მოგვიანებით', rom: 'mogvianebith', ru: 'Позже', en: 'Later', note: '' },
      { ka: 'სასწრაფოდ!', rom: 'sasts\'rapod!', ru: 'Срочно! / Быстро!', en: 'Urgent! / Hurry!', note: '' },
    ]
  },
};

const FLASHCARDS = [
  // Место
  { ka: 'სახლი', rom: 'sakhli', ru: 'дом', en: 'house', category: 'Место' },
  { ka: 'ქუჩა', rom: 'kucha', ru: 'улица', en: 'street', category: 'Место' },
  { ka: 'ქალაქი', rom: 'kalaki', ru: 'город', en: 'city', category: 'Место' },
  { ka: 'სასტუმრო', rom: 'sastumro', ru: 'отель', en: 'hotel', category: 'Место' },
  { ka: 'სადგური', rom: 'sadguri', ru: 'станция', en: 'station', category: 'Место' },
  { ka: 'მოედანი', rom: 'moedani', ru: 'площадь', en: 'square', category: 'Место' },
  { ka: 'პარკი', rom: 'p\'arki', ru: 'парк', en: 'park', category: 'Место' },
  { ka: 'ბანკი', rom: 'banki', ru: 'банк', en: 'bank', category: 'Место' },
  { ka: 'ეკლესია', rom: 'eklesia', ru: 'церковь', en: 'church', category: 'Место' },
  { ka: 'ციხე', rom: 'tsikhe', ru: 'крепость', en: 'fortress / castle', category: 'Место' },
  { ka: 'მუზეუმი', rom: 'muzeumi', ru: 'музей', en: 'museum', category: 'Место' },
  { ka: 'ბაზარი', rom: 'bazari', ru: 'рынок', en: 'market', category: 'Место' },
  { ka: 'მაღაზია', rom: 'maghazia', ru: 'магазин', en: 'shop', category: 'Место' },
  { ka: 'კაფე', rom: 'kape', ru: 'кафе', en: 'cafe', category: 'Место' },

  // Природа
  { ka: 'მთა', rom: 'mtha', ru: 'гора', en: 'mountain', category: 'Природа' },
  { ka: 'ზღვა', rom: 'zghva', ru: 'море', en: 'sea', category: 'Природа' },
  { ka: 'მდინარე', rom: 'mdinare', ru: 'река', en: 'river', category: 'Природа' },
  { ka: 'ტყე', rom: "t'qe", ru: 'лес', en: 'forest', category: 'Природа' },
  { ka: 'ცა', rom: 'tsa', ru: 'небо', en: 'sky', category: 'Природа' },
  { ka: 'მზე', rom: 'mze', ru: 'солнце', en: 'sun', category: 'Природа' },
  { ka: 'წვიმა', rom: "ts'vima", ru: 'дождь', en: 'rain', category: 'Природа' },
  { ka: 'ქარი', rom: 'kari', ru: 'ветер', en: 'wind', category: 'Природа' },
  { ka: 'თოვლი', rom: 'tovli', ru: 'снег', en: 'snow', category: 'Природа' },
  { ka: 'ტბა', rom: "t'ba", ru: 'озеро', en: 'lake', category: 'Природа' },

  // Еда
  { ka: 'წყალი', rom: "ts'q'ali", ru: 'вода', en: 'water', category: 'Еда' },
  { ka: 'პური', rom: "p'uri", ru: 'хлеб', en: 'bread', category: 'Еда' },
  { ka: 'ყავა', rom: "q'ava", ru: 'кофе', en: 'coffee', category: 'Еда' },
  { ka: 'ღვინო', rom: 'ghvino', ru: 'вино', en: 'wine', category: 'Еда' },
  { ka: 'ხინკალი', rom: 'khinkali', ru: 'хинкали', en: 'khinkali (dumplings)', category: 'Еда' },
  { ka: 'ხაჭაპური', rom: "khach'ap'uri", ru: 'хачапури', en: 'khachapuri (cheese bread)', category: 'Еда' },
  { ka: 'ხილი', rom: 'khili', ru: 'фрукты', en: 'fruit', category: 'Еда' },
  { ka: 'ბოსტნეული', rom: 'bostneuli', ru: 'овощи', en: 'vegetables', category: 'Еда' },
  { ka: 'ხორცი', rom: 'khortsi', ru: 'мясо', en: 'meat', category: 'Еда' },
  { ka: 'თევზი', rom: 'tevzi', ru: 'рыба', en: 'fish', category: 'Еда' },
  { ka: 'ყველი', rom: "q'veli", ru: 'сыр', en: 'cheese', category: 'Еда' },
  { ka: 'კვერცხი', rom: "k'vertskhi", ru: 'яйцо', en: 'egg', category: 'Еда' },
  { ka: 'რძე', rom: 'rdze', ru: 'молоко', en: 'milk', category: 'Еда' },
  { ka: 'მწვადი', rom: 'mtsvadi', ru: 'шашлык', en: 'shashlik (Georgian BBQ)', category: 'Еда' },

  // Семья
  { ka: 'დედა', rom: 'deda', ru: 'мама', en: 'mom', category: 'Семья' },
  { ka: 'მამა', rom: 'mama', ru: 'папа', en: 'dad', category: 'Семья' },
  { ka: 'და', rom: 'da', ru: 'сестра', en: 'sister', category: 'Семья' },
  { ka: 'ძმა', rom: 'dzma', ru: 'брат', en: 'brother', category: 'Семья' },
  { ka: 'ბებია', rom: 'bebia', ru: 'бабушка', en: 'grandmother', category: 'Семья' },
  { ka: 'ბაბუა', rom: 'babua', ru: 'дедушка', en: 'grandfather', category: 'Семья' },
  { ka: 'შვილი', rom: 'shvili', ru: 'ребёнок / дитя', en: 'child / offspring', category: 'Семья' },
  { ka: 'ოჯახი', rom: 'ojakhi', ru: 'семья', en: 'family', category: 'Семья' },

  // Люди
  { ka: 'მეგობარი', rom: 'megobari', ru: 'друг', en: 'friend', category: 'Люди' },
  { ka: 'კაცი', rom: "k'atsi", ru: 'мужчина', en: 'man', category: 'Люди' },
  { ka: 'ქალი', rom: 'kali', ru: 'женщина', en: 'woman', category: 'Люди' },
  { ka: 'ბავშვი', rom: 'bavshvi', ru: 'ребёнок', en: 'child', category: 'Люди' },
  { ka: 'სტუმარი', rom: 'stumari', ru: 'гость', en: 'guest', category: 'Люди' },

  // Числа
  { ka: 'ერთი', rom: 'erti', ru: 'один (1)', en: 'one (1)', category: 'Числа' },
  { ka: 'ორი', rom: 'ori', ru: 'два (2)', en: 'two (2)', category: 'Числа' },
  { ka: 'სამი', rom: 'sami', ru: 'три (3)', en: 'three (3)', category: 'Числа' },
  { ka: 'ოთხი', rom: 'otkhi', ru: 'четыре (4)', en: 'four (4)', category: 'Числа' },
  { ka: 'ხუთი', rom: 'khuti', ru: 'пять (5)', en: 'five (5)', category: 'Числа' },
  { ka: 'ექვსი', rom: 'ekvsi', ru: 'шесть (6)', en: 'six (6)', category: 'Числа' },
  { ka: 'შვიდი', rom: 'shvidi', ru: 'семь (7)', en: 'seven (7)', category: 'Числа' },
  { ka: 'რვა', rom: 'rva', ru: 'восемь (8)', en: 'eight (8)', category: 'Числа' },
  { ka: 'ცხრა', rom: 'tskhra', ru: 'девять (9)', en: 'nine (9)', category: 'Числа' },
  { ka: 'ათი', rom: 'ati', ru: 'десять (10)', en: 'ten (10)', category: 'Числа' },
  { ka: 'ოცი', rom: 'otsi', ru: 'двадцать (20)', en: 'twenty (20)', category: 'Числа' },
  { ka: 'ასი', rom: 'asi', ru: 'сто (100)', en: 'hundred (100)', category: 'Числа' },

  // Прилагательные
  { ka: 'კარგი', rom: "k'argi", ru: 'хороший', en: 'good', category: 'Прилагат.' },
  { ka: 'ცუდი', rom: 'tsudi', ru: 'плохой', en: 'bad', category: 'Прилагат.' },
  { ka: 'დიდი', rom: 'didi', ru: 'большой', en: 'big', category: 'Прилагат.' },
  { ka: 'პატარა', rom: "p'at'ara", ru: 'маленький', en: 'small', category: 'Прилагат.' },
  { ka: 'ლამაზი', rom: 'lamazi', ru: 'красивый', en: 'beautiful', category: 'Прилагат.' },
  { ka: 'ახალი', rom: 'akhali', ru: 'новый', en: 'new', category: 'Прилагат.' },
  { ka: 'ძველი', rom: 'dzveli', ru: 'старый', en: 'old', category: 'Прилагат.' },
  { ka: 'ცხელი', rom: 'tskheli', ru: 'горячий', en: 'hot', category: 'Прилагат.' },
  { ka: 'ცივი', rom: 'tsivi', ru: 'холодный', en: 'cold', category: 'Прилагат.' },
  { ka: 'გემრიელი', rom: 'gemrieli', ru: 'вкусный', en: 'delicious / tasty', category: 'Прилагат.' },
  { ka: 'ძვირი', rom: 'dzviri', ru: 'дорогой', en: 'expensive', category: 'Прилагат.' },
  { ka: 'იაფი', rom: 'iapi', ru: 'дешёвый', en: 'cheap', category: 'Прилагат.' },
  { ka: 'სწრაფი', rom: "sts'rapi", ru: 'быстрый', en: 'fast', category: 'Прилагат.' },
  { ka: 'ნელი', rom: 'neli', ru: 'медленный', en: 'slow', category: 'Прилагат.' },

  // Транспорт
  { ka: 'მანქანა', rom: 'manqana', ru: 'машина', en: 'car', category: 'Транспорт' },
  { ka: 'ავტობუსი', rom: 'avtobusi', ru: 'автобус', en: 'bus', category: 'Транспорт' },
  { ka: 'მეტრო', rom: 'metro', ru: 'метро', en: 'metro / subway', category: 'Транспорт' },
  { ka: 'ტაქსი', rom: 'taksi', ru: 'такси', en: 'taxi', category: 'Транспорт' },
  { ka: 'მატარებელი', rom: 'matarebeli', ru: 'поезд', en: 'train', category: 'Транспорт' },
  { ka: 'თვითმფრინავი', rom: 'tvitmprinavi', ru: 'самолёт', en: 'airplane', category: 'Транспорт' },
  { ka: 'ველოსიპედი', rom: 'velosip\'edi', ru: 'велосипед', en: 'bicycle', category: 'Транспорт' },
  { ka: 'გზა', rom: 'gza', ru: 'дорога / путь', en: 'road / way', category: 'Транспорт' },

  // Время
  { ka: 'დღე', rom: 'dghe', ru: 'день', en: 'day', category: 'Время' },
  { ka: 'ღამე', rom: 'ghame', ru: 'ночь', en: 'night', category: 'Время' },
  { ka: 'დილა', rom: 'dila', ru: 'утро', en: 'morning', category: 'Время' },
  { ka: 'საღამო', rom: 'saghamo', ru: 'вечер', en: 'evening', category: 'Время' },
  { ka: 'კვირა', rom: 'kvira', ru: 'неделя', en: 'week', category: 'Время' },
  { ka: 'თვე', rom: 'tve', ru: 'месяц', en: 'month', category: 'Время' },
  { ka: 'წელი', rom: 'tseli', ru: 'год', en: 'year', category: 'Время' },
  { ka: 'ახლა', rom: 'akhla', ru: 'сейчас', en: 'now', category: 'Время' },
  { ka: 'დღეს', rom: 'dghes', ru: 'сегодня', en: 'today', category: 'Время' },
  { ka: 'ხვალ', rom: 'khval', ru: 'завтра', en: 'tomorrow', category: 'Время' },

  // Цвета
  { ka: 'წითელი', rom: "ts'iteli", ru: 'красный', en: 'red', category: 'Цвета' },
  { ka: 'ლურჯი', rom: 'lurji', ru: 'синий', en: 'blue', category: 'Цвета' },
  { ka: 'მწვანე', rom: 'mtsvane', ru: 'зелёный', en: 'green', category: 'Цвета' },
  { ka: 'შავი', rom: 'shavi', ru: 'чёрный', en: 'black', category: 'Цвета' },
  { ka: 'თეთრი', rom: 'tetri', ru: 'белый', en: 'white', category: 'Цвета' },
  { ka: 'ყვითელი', rom: "q'viteli", ru: 'жёлтый', en: 'yellow', category: 'Цвета' },
  { ka: 'ნარინჯისფერი', rom: 'narinjisperi', ru: 'оранжевый', en: 'orange', category: 'Цвета' },
  { ka: 'ვარდისფერი', rom: 'vardisperi', ru: 'розовый', en: 'pink', category: 'Цвета' },
];

const TIPS = [
  {
    icon: '🍷',
    title: 'Грузинское вино и тост',
    title_en: 'Georgian Wine & Toasts',
    text: 'Грузия — родина виноделия (8000 лет!). Когда поднимают тост «გაუმარჯოს!» (gaumarjos!), ответьте тем же. Отказываться от угощения — невежливо, поэтому лучше скажите «ოდნავ» (odnav) — «чуть-чуть».',
    text_en: 'Georgia is the birthplace of winemaking (8,000 years!). When a toast «გაუმარჯოს!» (gaumarjos!) is raised, echo it back. Refusing a drink is impolite — instead say «ოდნავ» (odnav) meaning "just a little".',
    color: '#8B1A1A'
  },
  {
    icon: '🏠',
    title: 'Гостеприимство — святое',
    title_en: 'Hospitality is Sacred',
    text: 'Грузины невероятно гостеприимны. Если вас пригласили домой — соглашайтесь! Принесите что-нибудь сладкое или вино. Слово «სტუმარი» (stumari, гость) — почётное звание.',
    text_en: 'Georgians are extraordinarily hospitable. If you\'re invited into a home — go! Bring something sweet or a bottle of wine. The word «სტუმარი» (stumari, guest) is an honoured title.',
    color: '#1A5C1A'
  },
  {
    icon: '⛪',
    title: 'Церкви и храмы',
    title_en: 'Churches & Monasteries',
    text: 'Перед входом в церковь женщинам нужно покрыть голову и плечи. У входов обычно лежат платки. Фотографировать можно, но тихо и уважительно.',
    text_en: 'Before entering a church, women should cover their head and shoulders. Scarves are usually available at the entrance. Photography is allowed but be quiet and respectful.',
    color: '#5C4A1A'
  },
  {
    icon: '🤝',
    title: 'Язык жестов',
    title_en: 'Gestures & Body Language',
    text: 'Кивок головой вниз — «да», влево-вправо — «нет». Это отличается от привычного! Также грузины очень тактильны: объятия и поцелуи в щёку при встрече — норма.',
    text_en: 'A downward nod means "yes", side-to-side means "no" — the opposite of what you\'re used to! Georgians are also very tactile: hugs and cheek kisses on meeting are completely normal.',
    color: '#1A3A5C'
  },
  {
    icon: '🍽️',
    title: 'Хинкали едят руками',
    title_en: 'How to Eat Khinkali',
    text: 'Хинкали держат за «хвостик» — он не едётся (считается неправильным это делать). Надкусите снизу, выпейте бульон, затем съешьте остальное. Хвостики на тарелке считают!',
    text_en: 'Hold khinkali by the "knob" at the top — don\'t eat it (that\'s considered bad form). Bite from the bottom, sip the broth, then eat the rest. The knobs left on the plate are counted!',
    color: '#5C1A3A'
  },
  {
    icon: '💰',
    title: 'Деньги и чаевые',
    title_en: 'Money & Tipping',
    text: 'Валюта — Лари (GEL). Чаевые в ресторанах обычно 10%, можно оставить наличными. Во многих местах принимают карты, но наличные в маленьких заведениях обязательны.',
    text_en: 'Currency is the Lari (GEL). Restaurant tips are usually 10%, left in cash. Cards are accepted in most places, but small establishments and markets prefer cash.',
    color: '#2A5C3A'
  },
  {
    icon: '🚗',
    title: 'Транспорт',
    title_en: 'Getting Around',
    text: 'Маршрутки — основной вид транспорта. Оплата наличными или картой Metromoney. В Тбилиси есть метро (2 линии). Такси через Bolt или Yandex Go — дёшево и удобно.',
    text_en: 'Marshrutkas (minibuses) are the main transport. Pay by cash or Metromoney card. Tbilisi has a metro (2 lines). Taxis via Bolt or Yandex Go are cheap and convenient.',
    color: '#3A2A5C'
  },
  {
    icon: '🗣️',
    title: 'Говорите по-грузински!',
    title_en: 'Speak Georgian!',
    text: 'Любая попытка говорить по-грузински вызывает бурную радость у местных! Даже простое «გამარჯობა» и «გმადლობ» растопит любое сердце. Не бойтесь ошибаться!',
    text_en: 'Any attempt to speak Georgian brings huge joy to locals! Even a simple «გამარჯობა» (gamarjoba) and «გმადლობ» (gmadlob) will melt any heart. Don\'t be afraid to make mistakes!',
    color: '#1A4A5C'
  },
  {
    icon: '📅',
    title: 'Праздники и традиции',
    title_en: 'Holidays & Traditions',
    text: 'Гиоргоба (Св. Георгий) — 23 ноября, главный праздник. Новый год грузины встречают дважды: 1 января и 14 января. Рождество — 7 января. В эти дни всё может быть закрыто.',
    text_en: 'Giorgoba (St. George\'s Day) — 23 November, the main holiday. New Year is celebrated twice: January 1st and January 14th. Christmas is January 7th. Many places close on these days.',
    color: '#5C3A1A'
  },
  {
    icon: '🌿',
    title: 'Специи и зелень',
    title_en: 'Spices & Herbs',
    text: 'Грузинская кухня использует много зелени: кинза, петрушка, эстрагон. Если не переносите кинзу — скажите «კინძი არ მინდა» (kindzi ar minda) — «кинзу не хочу».',
    text_en: 'Georgian cuisine uses lots of fresh herbs: cilantro, parsley, tarragon. If you dislike cilantro, say «კინძი არ მინდა» (kindzi ar minda) — "no cilantro please".',
    color: '#2A5C2A'
  },
  {
    icon: '🔢',
    title: 'Система счёта — особенная',
    title_en: 'The Special Number System',
    text: 'Грузинский счёт основан на числе 20 (как французский!). 40 = «ორმოცი» (ormotsi) — «дважды двадцать». 60 = «სამოცი» (samotsi) — «трижды двадцать». Для торговли хватит 1-10 и «сколько стоит?»',
    text_en: 'Georgian counting is based on 20 (like French!). 40 = «ორმოცი» (ormotsi) — "twice twenty". 60 = «სამოცი» (samotsi) — "three times twenty". For shopping, knowing 1-10 and "how much?" is enough.',
    color: '#1A2A5C'
  },
  {
    icon: '📱',
    title: 'Связь и интернет',
    title_en: 'Connectivity & SIM Cards',
    text: 'SIM-карту (Magti, Beeline, Silknet) можно купить в аэропорту или салоне. ~5 GEL за карту + пакет данных. Wi-Fi есть почти везде. Google Maps отлично работает в Грузии.',
    text_en: 'SIM cards (Magti, Beeline, Silknet) can be bought at the airport or phone shops. ~5 GEL for a card + data package. Wi-Fi is almost everywhere. Google Maps works great in Georgia.',
    color: '#2A4A3A'
  },
  {
    icon: '🏔️',
    title: 'Регионы и диалекты',
    title_en: 'Regions & Dialects',
    text: 'В Аджарии (Батуми) слышится турецкое влияние. В горных районах (Сванетия, Кахетия) свои диалекты. Литературный грузинский понимают везде. Кахетия — главный винодельческий регион.',
    text_en: 'Adjara (Batumi) has Turkish influence in its culture. Mountain regions (Svaneti, Kakheti) have their own dialects. Standard Georgian is understood everywhere. Kakheti is the main wine region.',
    color: '#3A4A1A'
  },
  {
    icon: '🛡️',
    title: 'Безопасность',
    title_en: 'Safety',
    text: 'Грузия — одна из самых безопасных стран для туристов. Насильственные преступления редки. Берегите телефон и сумку в толпе на Руставели и Сухом мосту. Ночью центр Тбилиси живой и безопасный.',
    text_en: 'Georgia is one of the safest countries for tourists. Violent crime is rare. Watch your phone and bag in crowds on Rustaveli Avenue and the Dry Bridge market. Tbilisi city centre is lively and safe at night.',
    color: '#4A2A3A'
  },
  {
    icon: '🌡️',
    title: 'Погода и одежда',
    title_en: 'Weather & What to Wear',
    text: 'Тбилиси — жаркое лето (35°C+), мягкая зима. Батуми — субтропики, влажно. Горы: даже летом нужна тёплая куртка выше 2000м. Лучшее время для путешествия — май-июнь и сентябрь-октябрь.',
    text_en: 'Tbilisi: hot summers (35°C+), mild winters. Batumi: subtropical, humid. Mountains: even in summer bring a warm jacket above 2000m. Best travel times: May-June and September-October.',
    color: '#1A4A2A'
  },
];
